/*
 * NextGen Connect Client API
 *
 * Swagger documentation for the NextGen Connect Client API.
 *
 * The version of the OpenAPI document: 3.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OpenapiGenerator.MirthConnect311.Client.OpenAPIDateConverter;

namespace OpenapiGenerator.MirthConnect311.Model
{
    /// <summary>
    /// ChannelSummary
    /// </summary>
    [DataContract(Name = "ChannelSummary")]
    public partial class ChannelSummary : IEquatable<ChannelSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelSummary" /> class.
        /// </summary>
        /// <param name="channelId">channelId.</param>
        /// <param name="deleted">deleted.</param>
        /// <param name="undeployed">undeployed.</param>
        /// <param name="channelStatus">channelStatus.</param>
        public ChannelSummary(string channelId = default(string), bool deleted = default(bool), bool undeployed = default(bool), ChannelStatus channelStatus = default(ChannelStatus))
        {
            this.ChannelId = channelId;
            this.Deleted = deleted;
            this.Undeployed = undeployed;
            this.ChannelStatus = channelStatus;
        }

        /// <summary>
        /// Gets or Sets ChannelId
        /// </summary>
        [DataMember(Name = "channelId", EmitDefaultValue = false)]
        public string ChannelId { get; set; }

        /// <summary>
        /// Gets or Sets Deleted
        /// </summary>
        [DataMember(Name = "deleted", EmitDefaultValue = true)]
        public bool Deleted { get; set; }

        /// <summary>
        /// Gets or Sets Undeployed
        /// </summary>
        [DataMember(Name = "undeployed", EmitDefaultValue = true)]
        public bool Undeployed { get; set; }

        /// <summary>
        /// Gets or Sets ChannelStatus
        /// </summary>
        [DataMember(Name = "channelStatus", EmitDefaultValue = false)]
        public ChannelStatus ChannelStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChannelSummary {\n");
            sb.Append("  ChannelId: ").Append(ChannelId).Append("\n");
            sb.Append("  Deleted: ").Append(Deleted).Append("\n");
            sb.Append("  Undeployed: ").Append(Undeployed).Append("\n");
            sb.Append("  ChannelStatus: ").Append(ChannelStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChannelSummary);
        }

        /// <summary>
        /// Returns true if ChannelSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of ChannelSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChannelSummary input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ChannelId == input.ChannelId ||
                    (this.ChannelId != null &&
                    this.ChannelId.Equals(input.ChannelId))
                ) && 
                (
                    this.Deleted == input.Deleted ||
                    this.Deleted.Equals(input.Deleted)
                ) && 
                (
                    this.Undeployed == input.Undeployed ||
                    this.Undeployed.Equals(input.Undeployed)
                ) && 
                (
                    this.ChannelStatus == input.ChannelStatus ||
                    (this.ChannelStatus != null &&
                    this.ChannelStatus.Equals(input.ChannelStatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChannelId != null)
                {
                    hashCode = (hashCode * 59) + this.ChannelId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Deleted.GetHashCode();
                hashCode = (hashCode * 59) + this.Undeployed.GetHashCode();
                if (this.ChannelStatus != null)
                {
                    hashCode = (hashCode * 59) + this.ChannelStatus.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
