/*
 * NextGen Connect Client API
 *
 * Swagger documentation for the NextGen Connect Client API.
 *
 * The version of the OpenAPI document: 3.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OpenapiGenerator.MirthConnect311.Client.OpenAPIDateConverter;

namespace OpenapiGenerator.MirthConnect311.Model
{
    /// <summary>
    /// CodeTemplateUpdateResult
    /// </summary>
    [DataContract(Name = "CodeTemplateUpdateResult")]
    public partial class CodeTemplateUpdateResult : IEquatable<CodeTemplateUpdateResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CodeTemplateUpdateResult" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="newRevision">newRevision.</param>
        /// <param name="newLastModified">newLastModified.</param>
        /// <param name="cause">cause.</param>
        public CodeTemplateUpdateResult(bool success = default(bool), int newRevision = default(int), DateTime newLastModified = default(DateTime), CodeTemplateLibrarySaveResultCause cause = default(CodeTemplateLibrarySaveResultCause))
        {
            this.Success = success;
            this.NewRevision = newRevision;
            this.NewLastModified = newLastModified;
            this.Cause = cause;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets NewRevision
        /// </summary>
        [DataMember(Name = "newRevision", EmitDefaultValue = false)]
        public int NewRevision { get; set; }

        /// <summary>
        /// Gets or Sets NewLastModified
        /// </summary>
        [DataMember(Name = "newLastModified", EmitDefaultValue = false)]
        public DateTime NewLastModified { get; set; }

        /// <summary>
        /// Gets or Sets Cause
        /// </summary>
        [DataMember(Name = "cause", EmitDefaultValue = false)]
        public CodeTemplateLibrarySaveResultCause Cause { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CodeTemplateUpdateResult {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  NewRevision: ").Append(NewRevision).Append("\n");
            sb.Append("  NewLastModified: ").Append(NewLastModified).Append("\n");
            sb.Append("  Cause: ").Append(Cause).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CodeTemplateUpdateResult);
        }

        /// <summary>
        /// Returns true if CodeTemplateUpdateResult instances are equal
        /// </summary>
        /// <param name="input">Instance of CodeTemplateUpdateResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CodeTemplateUpdateResult input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Success == input.Success ||
                    this.Success.Equals(input.Success)
                ) && 
                (
                    this.NewRevision == input.NewRevision ||
                    this.NewRevision.Equals(input.NewRevision)
                ) && 
                (
                    this.NewLastModified == input.NewLastModified ||
                    (this.NewLastModified != null &&
                    this.NewLastModified.Equals(input.NewLastModified))
                ) && 
                (
                    this.Cause == input.Cause ||
                    (this.Cause != null &&
                    this.Cause.Equals(input.Cause))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Success.GetHashCode();
                hashCode = (hashCode * 59) + this.NewRevision.GetHashCode();
                if (this.NewLastModified != null)
                {
                    hashCode = (hashCode * 59) + this.NewLastModified.GetHashCode();
                }
                if (this.Cause != null)
                {
                    hashCode = (hashCode * 59) + this.Cause.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
