/*
 * NextGen Connect Client API
 *
 * Swagger documentation for the NextGen Connect Client API.
 *
 * The version of the OpenAPI document: 3.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace OpenapiGenerator.MirthConnect311.Api
{
    public class MessageWriterOptions
    {
    }
}